version: 2
updates:
  # Backend (Node.js) dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'America/Sao_Paulo'
    open-pull-requests-limit: 10
    reviewers:
      - 'lascmmg-team'
    assignees:
      - 'lascmmg-team'
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'security'
    allow:
      - dependency-type: 'direct'
      - dependency-type: 'indirect'
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: 'express'
        update-types: ['version-update:semver-major']
      - dependency-name: 'jsonwebtoken'
        update-types: ['version-update:semver-major']
      - dependency-name: 'bcrypt'
        update-types: ['version-update:semver-major']
    groups:
      security-updates:
        patterns:
          - 'helmet'
          - 'express-rate-limit'
          - 'xss-clean'
          - 'cors'
        update-types:
          - 'security-update'
      eslint-updates:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
        update-types:
          - 'minor'
          - 'patch'

  # Frontend (React) dependencies
  - package-ecosystem: 'npm'
    directory: '/frontend-react'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '10:00'
      timezone: 'America/Sao_Paulo'
    open-pull-requests-limit: 10
    reviewers:
      - 'lascmmg-team'
    assignees:
      - 'lascmmg-team'
    commit-message:
      prefix: 'chore(deps-frontend)'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'frontend'
      - 'security'
    allow:
      - dependency-type: 'direct'
      - dependency-type: 'indirect'
    ignore:
      # Ignore major version updates for React and core libraries
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-major']
      - dependency-name: 'vite'
        update-types: ['version-update:semver-major']
    groups:
      react-updates:
        patterns:
          - 'react'
          - 'react-*'
          - '@types/react*'
        update-types:
          - 'minor'
          - 'patch'
      testing-updates:
        patterns:
          - 'vitest'
          - 'cypress'
          - '@testing-library/*'
        update-types:
          - 'minor'
          - 'patch'
      build-tools:
        patterns:
          - 'vite'
          - 'vite-*'
          - '@vitejs/*'
          - 'rollup'
          - 'rollup-*'
        update-types:
          - 'minor'
          - 'patch'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '09:00'
      timezone: 'America/Sao_Paulo'
    open-pull-requests-limit: 5
    reviewers:
      - 'lascmmg-team'
    assignees:
      - 'lascmmg-team'
    commit-message:
      prefix: 'chore(actions)'
      include: 'scope'
    labels:
      - 'github-actions'
      - 'ci-cd'
      - 'security'
