import {
  FaBars,
  FaCalendarAlt,
  FaChartBar,
  FaCog,
  FaEye,
  FaFileAlt,
  FaGamepad,
  FaHistory,
  FaList,
  FaPlus,
  FaPlusCircle,
  FaShieldAlt,
  FaSitemap,
  FaTachometerAlt,
  FaTrash,
  FaTrophy,
  FaUserPlus,
  FaUsers,
  FaUsersCog,
  FaUserShield,
} from 'react-icons/fa';

export const menuSections = {
  dashboard: {
    name: 'Dashboard',
    icon: FaTachometerAlt,
    path: '/',
    permission: null,
    description: 'Visão geral do sistema e métricas principais',
    color: 'primary',
  },
  tournaments: {
    name: 'Torneios',
    icon: FaTrophy,
    isDropdown: true,
    permission: null,
    description: 'Gestão de torneios',
    color: 'accent',
    items: [
      {
        name: 'Ver Torneios',
        path: '/tournaments',
        icon: FaEye,
        description: 'Visualizar todos os torneios',
      },
      {
        name: 'Chaveamentos',
        path: '/brackets',
        icon: FaSitemap,
        description: 'Sistema de chaves',
      },
      {
        name: 'Estatísticas',
        path: '/stats',
        icon: FaChartBar,
        description: 'Dados e métricas',
      },
    ],
  },
  players: {
    name: 'Jogadores',
    icon: FaUsers,
    path: '/players',
    permission: null,
    description: 'Gerenciar jogadores',
    color: 'secondary',
  },
  scores: {
    name: 'Placares',
    icon: FaGamepad,
    isDropdown: true,
    permission: null,
    description: 'Sistema de pontuação',
    color: 'success',
    items: [
      {
        name: 'Histórico',
        path: '/scores',
        icon: FaHistory,
        description: 'Histórico de partidas',
      },
      {
        name: 'Adicionar',
        path: '/add-score',
        icon: FaPlusCircle,
        description: 'Novo placar',
      },
    ],
  },
  admin: {
    name: 'Administração',
    icon: FaUserShield,
    isDropdown: true,
    permission: 'admin',
    description: 'Painel administrativo',
    color: 'danger',
    items: [
      {
        name: 'Painel Admin',
        path: '/admin',
        icon: FaBars,
        description: 'Dashboard administrativo',
      },
      {
        name: 'Ger. Torneios',
        path: '/admin/tournaments',
        icon: FaTrophy,
        description: 'Gerenciar torneios',
        submenu: [
          {
            name: 'Listar',
            path: '/admin/tournaments',
            icon: FaList,
            description: 'Lista de torneios',
          },
          {
            name: 'Criar',
            path: '/admin/tournaments/create',
            icon: FaPlus,
            description: 'Novo torneio',
          },
        ],
      },
      {
        name: 'Ger. Jogadores',
        path: '/admin/players',
        icon: FaUsers,
        description: 'Gerenciar jogadores',
        submenu: [
          {
            name: 'Listar',
            path: '/admin/players',
            icon: FaList,
            description: 'Lista de jogadores',
          },
          {
            name: 'Criar',
            path: '/admin/players/create',
            icon: FaUserPlus,
            description: 'Novo jogador',
          },
        ],
      },
      {
        name: 'Agendamento',
        path: '/admin/schedule',
        icon: FaCalendarAlt,
        description: 'Agenda de partidas',
        submenu: [
          {
            name: 'Geral',
            path: '/admin/schedule',
            icon: FaCalendarAlt,
            description: 'Agenda geral',
          },
          {
            name: 'Partidas',
            path: '/admin/match-schedule',
            icon: FaGamepad,
            description: 'Agenda de partidas',
          },
        ],
      },
      {
        name: 'Relatórios',
        path: '/admin/reports',
        icon: FaFileAlt,
        description: 'Relatórios e análises',
      },
      {
        name: 'Log Atividades',
        path: '/admin/activity-log',
        icon: FaHistory,
        description: 'Histórico de ações',
      },
      {
        name: 'Usuários',
        path: '/admin/users',
        icon: FaUsersCog,
        description: 'Gerenciar usuários',
      },
      {
        name: 'Segurança',
        path: '/admin/security',
        icon: FaShieldAlt,
        description: 'Configurações de segurança',
      },
      {
        name: 'Lixeira',
        path: '/admin/trash',
        icon: FaTrash,
        description: 'Itens excluídos',
      },
    ],
  },
  settings: {
    name: 'Configurações',
    icon: FaCog,
    path: '/settings',
    permission: null,
    description: 'Configurações do sistema',
    color: 'neutral',
  },
};
